### ISSUE TITLE
fusera 0.0.8 and CWL

### ISSUE THREAD

**Issue by saulakravitz** [mitre/fusera#115]
From Todd Pihl @ NCI

==============================
Sorry, v0.0.8 gives the same result:
 
 
cwl-runner mountfusera.yml mountthis.yml
/usr/local/bin/cwl-runner 1.0.20180622214234
Resolved 'mountfusera.yml' to 'file:///home/ubuntu/datalake/mountfusera.yml'
[job mountfusera.yml] /tmp/tmpjoetGB$ /home/ubuntu/bin/fusera \
    mount \
    --ngc \
    /home/ubuntu/datalake/prj_phs710EA_test.ngc \
    --accession \
    SRR2043622 \
    --location \
    s3.us-east-1 \
    /home/ubuntu/datalake/sddpmount
panic: user: Current not implemented on linux/amd64
 
goroutine 1 [running]:
github.com/mitre/fusera/cmd.myUserAndGroup(0x7fff438c0f05, 0x1f)
        /Users/mbianchi/src/github.com/mitre/fusera/cmd/mount.go:219 +0x295
github.com/mitre/fusera/cmd.mount(0xe55c00, 0xc4201b03f0, 0x1, 0x7, 0x0, 0x0)
        /Users/mbianchi/src/github.com/mitre/fusera/cmd/mount.go:146 +0x171
github.com/mitre/fusera/vendor/github.com/spf13/cobra.(*Command).execute(0xe55c00, 0xc4201b0380, 0x7, 0x7, 0xe55c00, 0xc4201b0380)
        /Users/mbianchi/src/github.com/mitre/fusera/vendor/github.com/spf13/cobra/command.go:762 +0x475
github.com/mitre/fusera/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xe55e60, 0xc420058058, 0x0, 0x4dcd27)
        /Users/mbianchi/src/github.com/mitre/fusera/vendor/github.com/spf13/cobra/command.go:852 +0x334
github.com/mitre/fusera/vendor/github.com/spf13/cobra.(*Command).Execute(0xe55e60, 0x0, 0x0)
        /Users/mbianchi/src/github.com/mitre/fusera/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/mitre/fusera/cmd.Execute()
        /Users/mbianchi/src/github.com/mitre/fusera/cmd/root.go:51 +0x2d
main.main()
        /Users/mbianchi/src/github.com/mitre/fusera/main.go:36 +0x20
[job mountfusera.yml] completed permanentFail
{}
Final process status is permanentFail

========================
Fusera is version 0.0.7 and I’m running an Ubuntu 16.04.4 VM on AWS.
 
If you want to look at the CWL I’ve used, I’ve got it in my github repo:  https://github.com/pihltd/datalake
 
mountfusera.yml tries to mount using a full command line approach, mountfusera_envvar.yml tries to use environment variables when possible.  Both give the same error.  mountthis.yml is the file with the variable values.
 
Both are run using cwl-runner 1.0. 20180622214234
 
$ cwl-runner mountfusera.yml mountthis.yml   or $ cwl-runner mountfusera_envvar.yml mountthis.yml
 
Both return this error:
 
cwl-runner mountfusera.yml mountthis.yml
/usr/local/bin/cwl-runner 1.0.20180622214234
Resolved 'mountfusera.yml' to 'file:///home/ubuntu/datalake/mountfusera.yml'
[job mountfusera.yml] /tmp/tmpcNRAhV$ /home/ubuntu/bin/fusera \
    mount \
    --ngc \
    /home/ubuntu/datalake/prj_phs710EA_test.ngc \
    --accession \
    SRR2043622 \
    --location \
    s3.us-east-1 \
    /home/ubuntu/datalake/sddpmount
panic: user: Current not implemented on linux/amd64
 
goroutine 1 [running]:
github.com/mitre/fusera/cmd.myUserAndGroup(0x7ffd9c1f4f05, 0x1f)
        /Users/travis/gopath/src/github.com/mitre/fusera/cmd/mount.go:194 +0x27e
github.com/mitre/fusera/cmd.mount(0xe282e0, 0xc4201d63f0, 0x1, 0x7, 0x0, 0x0)
        /Users/travis/gopath/src/github.com/mitre/fusera/cmd/mount.go:143 +0x148
github.com/mitre/fusera/vendor/github.com/spf13/cobra.(*Command).execute(0xe282e0, 0xc4201d6380, 0x7, 0x7, 0xe282e0, 0xc4201d6380)
        /Users/travis/gopath/src/github.com/mitre/fusera/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/mitre/fusera/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xe28540, 0x403dfc, 0xc42006e058, 0x0)
        /Users/travis/gopath/src/github.com/mitre/fusera/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/mitre/fusera/vendor/github.com/spf13/cobra.(*Command).Execute(0xe28540, 0x0, 0x13)
        /Users/travis/gopath/src/github.com/mitre/fusera/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/mitre/fusera/cmd.Execute()
        /Users/travis/gopath/src/github.com/mitre/fusera/cmd/root.go:51 +0x2d
main.main()
        /Users/travis/gopath/src/github.com/mitre/fusera/main.go:35 +0x20
[job mountfusera.yml] completed permanentFail
{}
Final process status is permanentFail
 
 
The part I think is coming from fusera is starts with the “panic” line and the following pointers to various fusera files.  Like I said earlier, from a bash command line, fusera works fine using exactly the same parameters as the cwl scripts.  There’s just something about running from cwl that’s causing a hiccup.

**Comment by saulakravitz** [comment]
From Eugene:
I’ve reproduced it from command line:
 
ubuntu@ip-10-137-205-50:~$ echo $USER
ubuntu
ubuntu@ip-10-137-205-50:~$  /opt/fusera/fusera mount -n /home/ubuntu/ngc.ngc -a /home/ubuntu/acc.txt -l s3.us-east-1 /home/ubuntu/fusemnt&
[1] 11298
ubuntu@ip-10-137-205-50:~$ ls fusemnt/
SRR520591  SRR520592  SRR520639
ubuntu@ip-10-137-205-50:~$ kill 11298
ubuntu@ip-10-137-205-50:~$ ls fusemnt/
[1]+  Done                    /opt/fusera/fusera mount -n /home/ubuntu/ngc.ngc -a /home/ubuntu/acc.txt -l s3.us-east-1 /home/ubuntu/fusemnt
ubuntu@ip-10-137-205-50:~$ unset USER
ubuntu@ip-10-137-205-50:~$ /opt/fusera/fusera mount -n /home/ubuntu/ngc.ngc -a /home/ubuntu/acc.txt -l s3.us-east-1 /home/ubuntu/fusemnt
panic: user: Current not implemented on linux/amd64
 
goroutine 1 [running]:
github.com/mitre/fusera/cmd.myUserAndGroup(0x7ffcb77f57f5, 0x14)
        /Users/mbianchi/src/github.com/mitre/fusera/cmd/mount.go:219 +0x295
github.com/mitre/fusera/cmd.mount(0xe55c00, 0xc4201aa3f0, 0x1, 0x7, 0x0, 0x0)
        /Users/mbianchi/src/github.com/mitre/fusera/cmd/mount.go:146 +0x171
github.com/mitre/fusera/vendor/github.com/spf13/cobra.(*Command).execute(0xe55c00, 0xc4201aa380, 0x7, 0x7, 0xe55c00, 0xc4201aa380)
        /Users/mbianchi/src/github.com/mitre/fusera/vendor/github.com/spf13/cobra/command.go:762 +0x475
github.com/mitre/fusera/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xe55e60, 0xc420056058, 0x0, 0x4dcd27)
        /Users/mbianchi/src/github.com/mitre/fusera/vendor/github.com/spf13/cobra/command.go:852 +0x334
github.com/mitre/fusera/vendor/github.com/spf13/cobra.(*Command).Execute(0xe55e60, 0x0, 0x0)
        /Users/mbianchi/src/github.com/mitre/fusera/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/mitre/fusera/cmd.Execute()
        /Users/mbianchi/src/github.com/mitre/fusera/cmd/root.go:51 +0x2d
main.main()
       /Users/mbianchi/src/github.com/mitre/fusera/main.go:36 +0x20
ubuntu@ip-10-137-205-50:~$
